// Gerado a partir de "Substituições Alimentares em kcal.xlsx" (valores da TACO).
// Energia em kcal por 100 g do alimento. Não editar à mão: a planilha é a fonte.
import type { CategoriaSubstituicao } from "./substituicoes";

export const ALIMENTOS: ReadonlyArray<readonly [CategoriaSubstituicao, string, number]> = [
  ["carboidrato", "Abacaxi, cru", 48.3],
  ["carboidrato", "Abiu, cru", 62.4],
  ["carboidrato", "Abóbora, cabotian, cozida", 48.0],
  ["carboidrato", "Ameixa, calda, enlatada", 182.8],
  ["carboidrato", "Ameixa, crua", 52.5],
  ["carboidrato", "Arroz cozido", 128.3],
  ["carboidrato", "Arroz cru", 357.8],
  ["carboidrato", "Atemóia, crua", 97.0],
  ["carboidrato", "Aveia, flocos, crua", 393.8],
  ["carboidrato", "Açaí, polpa, com xarope de guaraná e glucose", 110.3],
  ["carboidrato", "Baião de dois, arroz e feijão-de-corda", 135.7],
  ["carboidrato", "Banana", 98.2],
  ["carboidrato", "Banana, da terra, crua", 128.0],
  ["carboidrato", "Banana, doce em barra", 280.1],
  ["carboidrato", "Batata, baroa, cozida", 80.1],
  ["carboidrato", "Batata, baroa, crua", 101.0],
  ["carboidrato", "Batata, doce, cozida", 76.8],
  ["carboidrato", "Batata, doce, crua", 118.2],
  ["carboidrato", "Batata, inglesa, cozida", 51.6],
  ["carboidrato", "Batata, inglesa, crua", 64.4],
  ["carboidrato", "Batata, inglesa, frita", 267.2],
  ["carboidrato", "Batata, inglesa, sauté ou assada", 67.9],
  ["carboidrato", "Bebida láctea, pêssego", 55.2],
  ["carboidrato", "Beterraba, crua", 48.8],
  ["carboidrato", "Biscoito maisena", 442.8],
  ["carboidrato", "Biscoito recheado", 471.8],
  ["carboidrato", "Biscoito, polvilho doce", 437.5],
  ["carboidrato", "Biscoito, salgado", 431.7],
  ["carboidrato", "Bolinho de arroz", 273.5],
  ["carboidrato", "Bolo, pronto, aipim", 323.9],
  ["carboidrato", "Bolo, pronto, chocolate", 410.0],
  ["carboidrato", "Bolo, pronto, coco", 333.4],
  ["carboidrato", "Bolo, pronto, milho", 311.4],
  ["carboidrato", "Caju, cru", 43.1],
  ["carboidrato", "Caju, suco concentrado, envasado", 45.1],
  ["carboidrato", "Cajá-Manga, cru", 45.6],
  ["carboidrato", "Cana, caldo de", 65.3],
  ["carboidrato", "Canjica, branca, crua", 357.6],
  ["carboidrato", "Canjica, com leite integral", 112.5],
  ["carboidrato", "Caqui, chocolate, cru", 71.4],
  ["carboidrato", "Carambola, crua", 45.7],
  ["carboidrato", "Cará, cozido", 77.6],
  ["carboidrato", "Cará, cru", 95.6],
  ["carboidrato", "Cebola, crua", 39.4],
  ["carboidrato", "Cereais, milho", 363.3],
  ["carboidrato", "Cereais, mingau, milho", 394.4],
  ["carboidrato", "Ciriguela, crua", 75.6],
  ["carboidrato", "Cocada branca", 448.8],
  ["carboidrato", "Coentro, folhas desidratadas", 309.1],
  ["carboidrato", "Coxinha de frango, frita", 283.0],
  ["carboidrato", "Creme de arroz, pó", 386.0],
  ["carboidrato", "Creme de milho, pó", 333.0],
  ["carboidrato", "Cupuaçu, cru", 49.4],
  ["carboidrato", "Cupuaçu, polpa, congelada", 48.8],
  ["carboidrato", "Curau, milho verde", 78.4],
  ["carboidrato", "Curau, milho verde, mistura para", 402.3],
  ["carboidrato", "Cuscuz, de milho, cozido com sal", 113.5],
  ["carboidrato", "Cuscuz, paulista", 142.1],
  ["carboidrato", "Doce, de abóbora, cremoso", 198.9],
  ["carboidrato", "Doce, de leite, cremoso", 306.3],
  ["carboidrato", "Empada de frango, pré-cozida, assada", 358.2],
  ["carboidrato", "Ervilha, enlatada, drenada", 73.8],
  ["carboidrato", "Farinha (centeio, mandioca, milho, trigo, rosca, láctea)", 335.8],
  ["carboidrato", "Farinha, de arroz, enriquecida", 363.1],
  ["carboidrato", "Feijão, cozido", 76.4],
  ["carboidrato", "Feijão, cru", 329.0],
  ["carboidrato", "Figo, cru", 41.4],
  ["carboidrato", "Figo, enlatado, em calda", 184.4],
  ["carboidrato", "Fruta-pão, crua", 67.0],
  ["carboidrato", "Fécula, de mandioca", 330.9],
  ["carboidrato", "Geléia, mocotó, natural", 106.1],
  ["carboidrato", "Glicose de milho", 292.1],
  ["carboidrato", "Goiaba, com casca, crua", 54.2],
  ["carboidrato", "Goiaba, doce (pasta ou cascão)", 269.0],
  ["carboidrato", "Graviola, crua", 61.6],
  ["carboidrato", "Grão-de-bico, cru", 354.7],
  ["carboidrato", "Guandu, cru", 344.1],
  ["carboidrato", "Inhame, cru", 96.7],
  ["carboidrato", "Iogurte com sabor", 69.6],
  ["carboidrato", "Jabuticaba, crua", 58.1],
  ["carboidrato", "Jaca, crua", 87.9],
  ["carboidrato", "Jamelão, cru", 41.0],
  ["carboidrato", "Jurubeba, crua", 125.8],
  ["carboidrato", "Kiwi, cru", 51.1],
  ["carboidrato", "Laranja", 45.4],
  ["carboidrato", "Lasanha, massa fresca, cozida", 163.8],
  ["carboidrato", "Lasanha, massa fresca, crua", 220.3],
  ["carboidrato", "Leite, condensado", 312.6],
  ["carboidrato", "Leite, fermentado", 69.6],
  ["carboidrato", "Lentilha, cozida", 92.6],
  ["carboidrato", "Lentilha, crua", 339.1],
  ["carboidrato", "Macarrão, instantâneo", 435.9],
  ["carboidrato", "Macarrão, molho bolognesa", 119.5],
  ["carboidrato", "Macarrão, trigo, cru", 371.1],
  ["carboidrato", "Mamão, cru", 45.3],
  ["carboidrato", "Mamão, doce", 209.4],
  ["carboidrato", "Mandioca, cozida", 125.4],
  ["carboidrato", "Mandioca, crua", 151.4],
  ["carboidrato", "Mandioca, frita", 300.1],
  ["carboidrato", "Manga, crua", 72.5],
  ["carboidrato", "Maracujá, cru", 68.4],
  ["carboidrato", "Maria mole", 301.2],
  ["carboidrato", "Marmelada", 257.2],
  ["carboidrato", "Maçã", 62.5],
  ["carboidrato", "Mel, de abelha", 309.2],
  ["carboidrato", "Melado", 296.5],
  ["carboidrato", "Mexerica crua", 57.6],
  ["carboidrato", "Milho, amido, cru", 361.4],
  ["carboidrato", "Milho, fubá, cru", 353.5],
  ["carboidrato", "Milho, verde, cru", 138.2],
  ["carboidrato", "Milho, verde, enlatado, drenado", 97.6],
  ["carboidrato", "Mingau tradicional, pó", 373.4],
  ["carboidrato", "Nhoque, batata, cozido", 180.8],
  ["carboidrato", "Nêspera, crua", 42.5],
  ["carboidrato", "Pamonha, barra para cozimento, pré-cozida", 171.2],
  ["carboidrato", "Pastel recheado, cru", 288.7],
  ["carboidrato", "Pastel recheado, frito", 388.4],
  ["carboidrato", "Pastel, massa, crua", 310.2],
  ["carboidrato", "Paçoca, amendoim", 486.9],
  ["carboidrato", "Pinha, crua", 88.5],
  ["carboidrato", "Pinhão, cozido", 174.4],
  ["carboidrato", "Pipoca, com óleo de soja, sem sal", 448.3],
  ["carboidrato", "Pitanga, crua", 41.4],
  ["carboidrato", "Polenta, pré-cozida", 102.7],
  ["carboidrato", "Polvilho, doce", 351.2],
  ["carboidrato", "Pupunha, cozida", 218.5],
  ["carboidrato", "Pão, aveia, forma", 343.1],
  ["carboidrato", "Pão, trigo, soja ou milho, francês, integral ou sovado", 294.5],
  ["carboidrato", "Pêra", 53.3],
  ["carboidrato", "Pêssego, enlatado, em calda", 63.1],
  ["carboidrato", "Queijo, petit suisse, morango", 121.1],
  ["carboidrato", "Rapadura", 352.0],
  ["carboidrato", "Refrigerante", 45.6],
  ["carboidrato", "Romã, crua", 55.7],
  ["carboidrato", "Tabule", 57.5],
  ["carboidrato", "Tamarindo, cru", 275.7],
  ["carboidrato", "Tapioca, com manteiga", 347.8],
  ["carboidrato", "Tapioca, pura", 232],
  ["carboidrato", "Tomate, extrato", 60.9],
  ["carboidrato", "Torrada, pão francês", 377.4],
  ["carboidrato", "Uva", 52.9],
  ["carboidrato", "Uva, suco concentrado, envasado", 57.7],
  ["carboidrato", "Yakisoba", 112.8],
  ["proteina", "Abadejo, filé, assado", 111.6],
  ["proteina", "Abadejo, filé, cozido", 91.1],
  ["proteina", "Abadejo, filé, cru", 59.1],
  ["proteina", "Abadejo, filé, grelhado", 129.6],
  ["proteina", "Atum, conserva em óleo", 165.9],
  ["proteina", "Atum, fresco, cru", 117.5],
  ["proteina", "Bacalhau, cru ou refogado", 135.9],
  ["proteina", "Camarão, cozido", 90.0],
  ["proteina", "Camarão, cru", 47.2],
  ["proteina", "Caranguejo, cozido", 82.7],
  ["proteina", "Carne, bovina, acém, cozido", 212.4],
  ["proteina", "Carne, bovina, acém, cru", 136.6],
  ["proteina", "Carne, bovina, bucho, cozido", 133.0],
  ["proteina", "Carne, bovina, bucho, cru", 137.3],
  ["proteina", "Carne, bovina, capa de contra-filé, sem gordura, crua", 131.1],
  ["proteina", "Carne, bovina, capa de contra-filé, sem gordura, grelhada", 239.4],
  ["proteina", "Carne, bovina, charque, cozido", 262.8],
  ["proteina", "Carne, bovina, contra-filé, sem gordura, cru", 156.6],
  ["proteina", "Carne, bovina, contra-filé, sem gordura, grelhado", 193.7],
  ["proteina", "Carne, bovina, coxão duro, sem gordura, cozido", 216.6],
  ["proteina", "Carne, bovina, coxão duro, sem gordura, cru", 148.0],
  ["proteina", "Carne, bovina, coxão mole, sem gordura, cozido", 218.7],
  ["proteina", "Carne, bovina, coxão mole, sem gordura, cru", 169.1],
  ["proteina", "Carne, bovina, filé mignon, sem gordura, cru", 142.9],
  ["proteina", "Carne, bovina, filé mignon, sem gordura, grelhado", 219.7],
  ["proteina", "Carne, bovina, flanco, sem gordura, cozido", 195.6],
  ["proteina", "Carne, bovina, flanco, sem gordura, cru", 141.5],
  ["proteina", "Carne, bovina, fígado, cru", 141.0],
  ["proteina", "Carne, bovina, fígado, grelhado", 225.0],
  ["proteina", "Carne, bovina, lagarto, cozido", 222.5],
  ["proteina", "Carne, bovina, lagarto, cru", 134.9],
  ["proteina", "Carne, bovina, maminha, crua", 152.8],
  ["proteina", "Carne, bovina, maminha, grelhada", 153.1],
  ["proteina", "Carne, bovina, miolo de alcatra, sem gordura, cru", 162.9],
  ["proteina", "Carne, bovina, miolo de alcatra, sem gordura, grelhado", 241.4],
  ["proteina", "Carne, bovina, músculo, sem gordura, cozido", 193.8],
  ["proteina", "Carne, bovina, músculo, sem gordura, cru", 141.6],
  ["proteina", "Carne, bovina, paleta, com gordura, crua", 158.7],
  ["proteina", "Carne, bovina, paleta, sem gordura, cozida", 193.7],
  ["proteina", "Carne, bovina, paleta, sem gordura, crua", 140.9],
  ["proteina", "Carne, bovina, patinho, sem gordura, cru", 133.5],
  ["proteina", "Carne, bovina, patinho, sem gordura, grelhado", 219.3],
  ["proteina", "Carne, bovina, picanha, sem gordura, crua", 133.5],
  ["proteina", "Carne, bovina, picanha, sem gordura, grelhada", 238.5],
  ["proteina", "Cação, posta, com farinha de trigo, frita", 208.3],
  ["proteina", "Cação, posta, cozida", 116.0],
  ["proteina", "Cação, posta, crua", 83.3],
  ["proteina", "Corimba, cru", 128.2],
  ["proteina", "Corvina grande, assada", 146.5],
  ["proteina", "Corvina grande, cozida", 100.1],
  ["proteina", "Corvina, crua", 101.0],
  ["proteina", "Dobradinha", 124.5],
  ["proteina", "Dourada de água doce, fresca", 131.2],
  ["proteina", "Frango, caipira, inteiro, sem pele, cozido", 195.8],
  ["proteina", "Frango, coxa, com pele, assada", 215.1],
  ["proteina", "Frango, coxa, sem pele, cozida", 167.4],
  ["proteina", "Frango, coxa, sem pele, crua", 119.9],
  ["proteina", "Frango, filé, à milanesa", 220.9],
  ["proteina", "Frango, fígado, cru", 106.5],
  ["proteina", "Frango, inteiro, sem pele, assado ou cozido", 187.3],
  ["proteina", "Frango, inteiro, sem pele, cru", 129.1],
  ["proteina", "Frango, peito, com pele, cru", 149.5],
  ["proteina", "Frango, peito, com pele, pronto", 211.7],
  ["proteina", "Frango, peito, sem pele, cru", 119.2],
  ["proteina", "Frango, peito, sem pele, pronto", 162.9],
  ["proteina", "Frango, sobrecoxa, sem pele, assada", 232.9],
  ["proteina", "Lambari, congelado, cru", 130.8],
  ["proteina", "Merluza, filé, assado", 121.9],
  ["proteina", "Merluza, filé, cru", 89.1],
  ["proteina", "Merluza, filé, frito", 191.6],
  ["proteina", "Ovo, de galinha, clara, cozida", 59.4],
  ["proteina", "Peru, assado", 163.1],
  ["proteina", "Peru, cru", 93.7],
  ["proteina", "Pescada, branca, crua", 110.9],
  ["proteina", "Pescada, branca, frita", 223.0],
  ["proteina", "Pescada, filé, cru", 107.2],
  ["proteina", "Pescada, filé, frito", 154.3],
  ["proteina", "Pescadinha, crua", 76.4],
  ["proteina", "Pintado, assado", 191.6],
  ["proteina", "Pintado, cru", 91.1],
  ["proteina", "Pintado, grelhado", 152.2],
  ["proteina", "Porco, bisteca, crua", 164.1],
  ["proteina", "Porco, lombo, assado", 210.2],
  ["proteina", "Porco, lombo, cru", 175.6],
  ["proteina", "Porco, pernil, assado", 262.3],
  ["proteina", "Porquinho, cru", 93.0],
  ["proteina", "Presunto, sem capa de gordura", 93.7],
  ["proteina", "Sarapatel", 123.0],
  ["proteina", "Sardinha, assada", 164.4],
  ["proteina", "Sardinha, frita", 257.0],
  ["proteina", "Sardinha, inteira, crua", 113.9],
  ["proteina", "Tucunaré, filé, congelado, cru", 87.7],
  ["proteina", "Whey protein 80%", 396],
  ["gordura", "Amendoim, torrado, salgado", 605.8],
  ["gordura", "Amêndoa", 580.7],
  ["gordura", "Azeite", 884],
  ["gordura", "Azeitona, preta, conserva", 194.2],
  ["gordura", "Azeitona, verde, conserva", 136.9],
  ["gordura", "Castanha-de-caju", 570.2],
  ["gordura", "Castanha-do-Brasil (Pará)", 643.0],
  ["gordura", "Coco, cru", 406.5],
  ["gordura", "Creme de Leite", 221.5],
  ["gordura", "Gergelim, semente", 583.5],
  ["gordura", "Leite, de coco", 166.2],
  ["gordura", "Linhaça, semente", 495.1],
  ["gordura", "Macaúba, crua", 404.3],
  ["gordura", "Maionese, tradicional com ovos", 302.2],
  ["gordura", "Manteiga ou margarina", 757.5],
  ["gordura", "Noz, crua", 620.1],
  ["gordura", "Ovo, gema, cozida", 352.7],
  ["gordura", "Ovo, inteiro, cozido", 145.7],
  ["gordura", "Ovo, inteiro, cru", 143.1],
  ["gordura", "Ovo, inteiro, frito", 240.2],
  ["gordura", "Paçoca, amendoim", 486.9],
  ["gordura", "Pequi, cru", 205.0],
  ["gordura", "Pé-de-moleque, amendoim", 503.2],
  ["gordura", "Queijo, minas, frescal", 264.3],
  ["gordura", "Queijo, minas, meia cura", 320.7],
  ["gordura", "Queijo, mozarela", 329.9],
  ["gordura", "Queijo, parmesão", 453.0],
  ["gordura", "Queijo, pasteurizado", 303.1],
  ["gordura", "Queijo, prato", 359.9],
  ["gordura", "Queijo, requeijão, cremoso", 256.6],
  ["gordura", "Sardinha, conserva em óleo", 285.0],
  ["gordura", "Vatapá", 254.9],
  ["gordura", "Óleos", 884],
];
